export const FRAUD_FLAG_CODES = [
  "GEO_ANOMALY",
  "VELOCITY_EXCEEDED",
  "CARD_TESTING_SUSPECTED",
  "AMOUNT_3X_AVERAGE",
  "UNUSUAL_CATEGORY",
  "VPN_DETECTED",
  "PROXY_IP",
  "NEW_DEVICE",
  "OFF_HOURS_ACTIVITY",
  "CARD_TESTING_PATTERN",
  "PATTERN_MATCH",
] as const;

export type FraudFlagCode = (typeof FRAUD_FLAG_CODES)[number];

export const ALERT_TYPE_LABELS: Record<string, string> = {
  VELOCITY: "VELOCITY ATTACK DETECTED",
  GEO_ANOMALY: "GEOGRAPHIC ANOMALY",
  AMOUNT_SPIKE: "AMOUNT SPIKE",
  NEW_DEVICE: "NEW DEVICE",
  VPN_DETECTED: "VPN / PROXY",
  PATTERN_MATCH: "PATTERN MATCH",
};
